services:
  django_backend:
    build:
      context: ./django_backend
    command: gunicorn django_backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - migrations
      - database
  react_frontend:
    build:
      context: ./react_frontend
    volumes:
      - react_build:/react_frontend/build
  migrations:
    image: django_react_app-django_backend
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate"
    depends_on:
      - database
  database:
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react_frontend
    depends_on:
      - django_backend
      - react_frontend
volumes:
  react_build: