
services:
  app:
    build: .
    volumes:
      - .:/src
    ports:
      - 8001:8001
    command: python3 manage.py runserver 0.0.0.0:8001
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}